In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("online_shoppers_intention.csv")
df.shape

(12330, 18)

In [ ]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [ ]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [ ]:
df.isnull().sum()
df.duplicated().sum()

np.int64(125)

In [ ]:
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean.duplicated().sum()

np.int64(125)

In [ ]:
df_clean = df_clean.drop_duplicates()

In [ ]:
df_clean.shape

(12205, 18)

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
df_clean.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

In [ ]:
df_clean["Month"].value_counts()

Month
May     3329
Nov     2982
Mar     1860
Dec     1706
Oct      549
Sep      448
Aug      433
Jul      432
June     285
Feb      181
Name: count, dtype: int64

In [ ]:
df_clean["VisitorType"].value_counts()

VisitorType
Returning_Visitor    10431
New_Visitor           1693
Other                   81
Name: count, dtype: int64

In [ ]:
df_clean["Weekend"].value_counts()

Weekend
False    9346
True     2859
Name: count, dtype: int64

In [ ]:
df_clean["Revenue"].value_counts()

Revenue
False    10297
True      1908
Name: count, dtype: int64

In [ ]:
df_clean["TotalPages"] = (
    df_clean["Administrative"]
    + df_clean["Informational"]
    + df_clean["ProductRelated"]
)

In [ ]:
df_clean[[
    "Administrative",
    "Informational",
    "ProductRelated",
    "TotalPages"
]].head()

   Administrative  Informational  ProductRelated  TotalPages
0               0              0               1           1
1               0              0               2           2
2               0              0               1           1
3               0              0               2           2
4               0              0              10          10

In [ ]:
df_clean["TotalDuration"] = (
    df_clean["Administrative_Duration"]
    + df_clean["Informational_Duration"]
    + df_clean["ProductRelated_Duration"]
)

In [ ]:
df_clean["Converted"] = df_clean["Revenue"].astype(int)

In [ ]:
df_clean[["Revenue", "Converted"]].head()

   Revenue  Converted
0    False          0
1    False          0
2    False          0
3    False          0
4    False          0

In [ ]:
df_clean["PagesPerSession"] = df_clean["TotalPages"]

In [ ]:
df_clean.shape

(12205, 22)

In [ ]:
df_clean.to_csv("ecommerce_cleaned.csv", index=False)

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

correlation = df_clean[
    ['TotalPages',
     'TotalDuration',
     'ProductRelated',
     'ProductRelated_Duration',
     'BounceRates',
     'ExitRates',
     'PageValues']
].corr()

print(correlation)

                         TotalPages  TotalDuration  ProductRelated  \
TotalPages                 1.000000       0.856760        0.997169
TotalDuration              0.856760       1.000000        0.852243
ProductRelated             0.997169       0.852243        1.000000
ProductRelated_Duration    0.859877       0.993887        0.860330
BounceRates               -0.202677      -0.179984       -0.192884
ExitRates                 -0.300198      -0.255009       -0.286082
PageValues                 0.060064       0.055660        0.054201

                         ProductRelated_Duration  BounceRates  ExitRates  \
TotalPages                              0.859877    -0.202677  -0.300198
TotalDuration                           0.993887    -0.179984  -0.255009
ProductRelated                          0.860330    -0.192884  -0.286082
ProductRelated_Duration                 1.000000    -0.173829  -0.245265
BounceRates                            -0.173829     1.000000   0.902144
ExitRates                              -0.245265     0.902144   1.000000
PageValues                              0.050923    -0.115799  -0.173627

                         PageValues
TotalPages                 0.060064
TotalDuration              0.055660
ProductRelated             0.054201
ProductRelated_Duration    0.050923
BounceRates               -0.115799
ExitRates                 -0.173627
PageValues                 1.000000

In [ ]:
from scipy.stats import pearsonr

r, p = pearsonr(
    df_clean['TotalPages'],
    df_clean['TotalDuration']
)

print("r =", r)
print("p =", p)

r = 0.8567601912991369
p = 0.0

In [ ]:
from scipy.stats import chi2_contingency

table = pd.crosstab(
    df['VisitorType'],
    df['Revenue']
)

print(table)

chi2, p, dof, expected = chi2_contingency(table)

print("Chi-square =", chi2)
print("p-value =", p)
print("Degrees of freedom =", dof)

Revenue            False  True
VisitorType
New_Visitor         1272    422
Other                 69     16
Returning_Visitor   9081   1470
Chi-square = 135.2519228192047
p-value = 4.269904152293867e-30
Degrees of freedom = 2

In [ ]:
visitor_conversion = df.groupby('VisitorType')['Revenue'].mean() * 100

print(visitor_conversion)

VisitorType
New_Visitor          24.911452
Other                18.823529
Returning_Visitor    13.932329
Name: Revenue, dtype: float64

In [ ]:
group_means = df_clean.groupby('Revenue')[
    ['TotalPages',
     'TotalDuration',
     'ProductRelated',
     'ProductRelated_Duration',
     'BounceRates',
     'ExitRates',
     'PageValues']
].mean()

print(group_means)

         TotalPages  TotalDuration  ProductRelated  ProductRelated_Duration  \
Revenue
False     31.651161    1188.215446       29.050403              1082.976881
True      52.389937    2053.304285       48.210168              1876.209615

         BounceRates  ExitRates  PageValues
Revenue
False       0.023197   0.045526    1.999985
True        0.005117   0.019555   27.264518

In [ ]:
from scipy.stats import mannwhitneyu

variables = [
    'TotalPages',
    'TotalDuration',
    'ProductRelated',
    'ProductRelated_Duration',
    'BounceRates',
    'ExitRates',
    'PageValues'
]

for variable in variables:

    revenue = df_clean[df_clean['Revenue'] == True][variable]
    non_revenue = df_clean[df_clean['Revenue'] == False][variable]

    stat, p = mannwhitneyu(
        revenue,
        non_revenue,
        alternative='two-sided'
    )

    print(variable)
    print("U statistic:", stat)
    print("p-value:", p)
    print("-" * 40)

TotalPages
U statistic: 12947567.5
p-value: 2.8312741332747465e-108
----------------------------------------
TotalDuration
U statistic: 13207262.5
p-value: 1.2043355669993277e-126
----------------------------------------
ProductRelated
U statistic: 12856227.0
p-value: 3.693607860403177e-102
----------------------------------------
ProductRelated_Duration
U statistic: 13145025.5
p-value: 4.183328282203313e-122
----------------------------------------
BounceRates
U statistic: 7686495.5
p-value: 1.0600897273692397e-56
----------------------------------------
ExitRates
U statistic: 5903681.5
p-value: 3.029893668139283e-169
----------------------------------------
PageValues
U statistic: 16951382.0
p-value: 0.0
----------------------------------------